### ISSUE TITLE
Outstanding rules to disable & usability issues

### ISSUE THREAD

**Issue by jtbandes** [foxglove/eslint-config#26]
This plugin & default configs have progressed a lot, but when migrating an existing project and writing new code there are still some things which we often disable: https://github.com/foxglove/rosbag/pull/8

- `@typescript-eslint/no-empty-function` – just turn off? is this guarding against any footguns that we know of?
- `@typescript-eslint/no-unsafe-member-access` – this makes it hard to use `any` typed objects. We usually prevent `any` via other rules, so this just adds extra steps to something that is already hard to work with.

    The one place we **_do_** normally have `any` is `catch(err)` — see [`@typescript-eslint/no-implicit-any-catch.md`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-implicit-any-catch.md) – but changing all our catches to `catch(e: unknown)` would probably be a huge hassle. The `no-unsafe-member-access` rule prevents us from doing `err.message`, but so would changing it to unknown 🤷 

    Studio currently has this in eslintrc:
    ```yaml
      # These are related to `any` types, which we generally don't have except from imports
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/no-unsafe-return": off
      "@typescript-eslint/no-unsafe-assignment": off
      "@typescript-eslint/no-unsafe-call": off
     ```

- `@typescript-eslint/restrict-template-expressions`: maybe turn off? Again there are some annoyances around `any`, which happens in catch clauses – so maybe we configure the rule as `[error, { allowBoolean: true, allowAny: true }]`? See also discussion in #12 

- Null vs undefined – in studio we ban `null` and it might be nice to extend this to other repos (at least our non-React repos). Currently though, there is a rule (maybe strict-boolean-expressions?) that adds `!= null` when auto-fixing, so ideally we would have something that enforces (and auto-fixes) `==/!=undefined` over `==/!=null`.

**Comment by defunctzombie** [comment]
Typescript 4.4 will default to unknown in catch variables https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#use-unknown-catch-variables

**Comment by jtbandes** [comment]
So are we gonna add `if (err instanceof Error) {` everywhere, `catch (err: any)` everywhere (and maybe do some work to convince our no-explicit-any lint rule that it's ok), or turn off that new TS flag?

**Comment by defunctzombie** [comment]
/shrug - dunno - in js anything can be thrown and unlike c++ we can't have catch clauses for a given type so its the wild west. Usually folks assume an Error instance is thrown but I've definitely seen codebases that throw strings.
